#!/usr/bin/env python3
"""
NTAG424 DNA Tag Provisioning Tool

Generates AES-128 keys for Secure Dynamic Messaging (SDM/SUN) and outputs
step-by-step instructions for NFC TagWriter by NXP (Android app).

Run once before the event. Stick the output keys in .env and follow the
instructions on your Android phone to program each tag.

Usage:
    python3 provision_nfc_tag.py
    python3 provision_nfc_tag.py --pda <CAMERA_PDA>
"""

import os
import sys
import secrets
import argparse

# Camera PDA for the Foundry event Jetson
DEFAULT_CAMERA_PDA = "ArQxL9kzhZ8QhJtNodnuMvkd3HGdkwSsTzbD4qD9QqKv"
BASE_URL = "https://mmoment.xyz"


def generate_keys():
    """Generate two random 16-byte AES-128 keys."""
    enc_key = secrets.token_bytes(16)
    mac_key = secrets.token_bytes(16)
    return enc_key, mac_key


def build_tag_url(camera_pda: str) -> str:
    """
    Build the URL template to write into the tag.

    The 32 zeros after e= are the placeholder for EncryptedPICCData (16 bytes = 32 hex chars).
    The 16 zeros after c= are the placeholder for SDMMAC (8 bytes = 16 hex chars).
    NFC TagWriter replaces these placeholders with real values on each tap.
    """
    return (
        f"{BASE_URL}/tap/{camera_pda}"
        f"?e=00000000000000000000000000000000"
        f"&c=0000000000000000"
    )


def write_env_file(enc_key: bytes, mac_key: bytes, camera_pda: str):
    """Write .env.nfc with the generated keys."""
    env_path = os.path.join(os.path.dirname(__file__), ".env.nfc")
    with open(env_path, "w") as f:
        f.write("# NTAG424 DNA SUN Keys - generated by provision_nfc_tag.py\n")
        f.write("# Add these to the camera service .env before deploying\n")
        f.write(f"# Camera PDA: {camera_pda}\n\n")
        f.write(f"NFC_SDM_ENC_KEY={enc_key.hex().upper()}\n")
        f.write(f"NFC_SDM_MAC_KEY={mac_key.hex().upper()}\n")
        f.write(f"NFC_REQUIRED=true\n")
        f.write(f"NFC_PRESENCE_TOKEN_SECRET={secrets.token_hex(32)}\n")
    print(f"\n  Saved keys to: {env_path}")


def print_instructions(enc_key: bytes, mac_key: bytes, camera_pda: str):
    tag_url = build_tag_url(camera_pda)

    print("\n" + "=" * 70)
    print("  NTAG424 DNA PROVISIONING KEYS")
    print("=" * 70)
    print(f"\n  Camera PDA : {camera_pda}")
    print(f"\n  SdmEncKey  : {enc_key.hex().upper()}")
    print(f"  SdmMACKey  : {mac_key.hex().upper()}")
    print(f"\n  Tag URL template:")
    print(f"  {tag_url}")

    print("\n" + "=" * 70)
    print("  NFC TagWriter by NXP — Step-by-Step Instructions")
    print("  (Install: play.google.com/store/apps/details?id=com.nxp.nfc.tagwriter)")
    print("=" * 70)

    print("""
STEP 1 — Open NFC TagWriter by NXP on your Android phone.

STEP 2 — Tap the tag to your phone back. The app will read its chip info.
          You should see "NTAG 424 DNA" — if not, it's the wrong chip.

STEP 3 — Tap "Write" → "New Dataset" → "Link (URI/URL)"

STEP 4 — Enter the URL template exactly as shown:""")
    print(f"\n          {tag_url}\n")

    print("""STEP 5 — Tap "More options" or the gear icon.

STEP 6 — Enable "SDM (Secure Dynamic Messaging)". You'll see a toggle.

STEP 7 — Configure SDM options:
          Mirror type:          EncryptedPICCData + SDMMAC
          UID mirroring:        ON
          SDMReadCtr mirror:    ON
          Encrypt PICC data:    ON

STEP 8 — When asked for SDM file read key (SdmEncKey / Key 2):""")
    print(f"          {enc_key.hex().upper()}\n")

    print("""STEP 9 — When asked for SDM MAC key (SdmMACKey / Key 3):""")
    print(f"          {mac_key.hex().upper()}\n")

    print("""STEP 10 — Tap "Save Dataset", then "Write Tag".
           Hold the phone near the tag until it confirms "Tag written".

STEP 11 — Test the tap: tap the tag again. Your phone should open a URL
           like: mmoment.xyz/tap/{pda}?e=A1B2C3...&c=F4E5D6...
           The e= and c= values are now DIFFERENT every tap — that's the crypto.

STEP 12 — Repeat for each tag. Each tag gets the same keys (all 5 tags
           share one key pair for this event — that's fine for a demo).

STEP 13 — Add the keys to docker-compose or .env on the Jetson:""")
    print(f"           NFC_SDM_ENC_KEY={enc_key.hex().upper()}")
    print(f"           NFC_SDM_MAC_KEY={mac_key.hex().upper()}")
    print(f"           NFC_REQUIRED=true")
    print()

    print("=" * 70)
    print("  KEY SECURITY NOTE")
    print("=" * 70)
    print("""
  - These keys are stored in .env.nfc in this scripts/ directory.
  - The same keys must be in the Jetson's docker-compose environment.
  - Once written to a tag, keys cannot be extracted from the chip.
  - If you lose the keys, the tags still work but the server can't verify them.
  - For a 2-week demo this key pair is fine to reuse across all 5 tags.
""")


def main():
    parser = argparse.ArgumentParser(description="Provision NTAG424 DNA tags for MMOMENT")
    parser.add_argument(
        "--pda",
        default=DEFAULT_CAMERA_PDA,
        help=f"Camera PDA (default: {DEFAULT_CAMERA_PDA})",
    )
    parser.add_argument(
        "--reuse-env",
        action="store_true",
        help="Reuse keys from existing .env.nfc instead of generating new ones",
    )
    args = parser.parse_args()

    env_path = os.path.join(os.path.dirname(__file__), ".env.nfc")

    if args.reuse_env and os.path.exists(env_path):
        print("Reusing existing keys from .env.nfc ...")
        enc_key = None
        mac_key = None
        with open(env_path) as f:
            for line in f:
                if line.startswith("NFC_SDM_ENC_KEY="):
                    enc_key = bytes.fromhex(line.strip().split("=", 1)[1])
                elif line.startswith("NFC_SDM_MAC_KEY="):
                    mac_key = bytes.fromhex(line.strip().split("=", 1)[1])
        if not enc_key or not mac_key:
            print("ERROR: Could not read keys from .env.nfc")
            sys.exit(1)
    else:
        print("Generating new AES-128 key pair...")
        enc_key, mac_key = generate_keys()
        write_env_file(enc_key, mac_key, args.pda)

    print_instructions(enc_key, mac_key, args.pda)


if __name__ == "__main__":
    main()
